taps:
  - heroku/brew
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions
apps:
  - bash-completion
  - boost
  - cmake
  - coreutils
  - cowsay
  - direnv
  - dockutil
  - dos2unix
  - ffmpeg
  - fwup
  - git
  - git-extras
  - gnupg
  - heroku
  - httpie
  - hub
  - imagemagick
  - lame
  - mas
  - mercurial
  - p7zip
  - pandoc
  - psgrep
  - qt
  - readline
  - ripgrep
  - ssh-copy-id
  - sphinx-doc
  - sqlite
  - subversion
  - tig
  - tldr
  - tree
  - unrar
  - vim
  - vorbis-tools
  - wget
  - wine
  - wxmac
  - yarn
  - youtube-dl
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting
cask-apps:
  - 1password
  - aerial
  - alfred
  - arduino
  - arq
  - atom
  - bartender
  - battle-net
  - blender
  - brave-browser
  - cardhop
  - choosy
  - controlplane
  - dash
  - docker
  - dropbox
  - duet
  - eagle
  - epic-games
  - firefox
  - font-cabin
  - font-chivo
  - font-cormorant
  - font-fira-code
  - font-fira-mono
  - font-fira-sans
  - font-inconsolata
  - font-montserrat
  - font-neuton
  - font-roboto
  - font-rubik
  - font-source-code-pro
  - forklift
  - ftdi-vcp-driver
  - google-chrome
  - google-chrome-canary
  - handbrake
  - harvest
  - hex-fiend
  - istat-menus
  - iterm2
  - java
  - kap
  - keepingyouawake
  - keybase
  - kitematic
  - knox
  - ksdiff
  - little-snitch
  - mactex
  - microsoft-office
  - ngrok
  - opera
  - path-finder
  - parallels
  - paw
  - postgres
  - qlmarkdown
  - quicklook-json
  - redis-app
  - silicon-labs-vcp-driver
  - sketchup
  - slack
  - slic3r
  - sourcetree
  - spotify
  - steam
  - textmate
  - the-unarchiver
  - transmission
  - tunnelbear
  - ultimaker-cura
  - visual-studio-code
  - visual-studio-code-insiders
  - virtualbox
  - vlc
  - vmware-fusion
  - wireshark
  - xquartz
